language: bash
os:
- osx
script: ./test.sh
before_install:
  - ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
install:
  - brew install rcmdnk/homebrew-file/brew-file
script: ./test.sh

