#language:
#  - c
#os:
#  - linux
#  - osx
#script: ./test.sh
#before_install:
#  - echo OSTYPE=$OSTYPE
#  - echo TRAVIS_OS_NAME=$TRAVIS_OS_NAME
#  - echo OSX=$OSX
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OSX!; fi
#env:
#  - PACKAGE=a
#  - PACKAGE=b
##  - ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
##python:
##  - "2.6"
##  - "2.7"
##  - "3.2"
##  - "3.3"
##  - "3.4"
##install:
##  - brew install rcmdnk/homebrew-file/brew-file

# Flowgrind also uses Coverity Scan. See https://scan.coverity.com/ for details.
language:
  - c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo linux!; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo osx!; fi
script: ./test.sh
