language: objective-c
branches:
  except:
    - /^v[0-9]/
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
  matrix:
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
before_install:
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && openssl aes-256-cbc -K $encrypted_43fa9741277b_key -iv $encrypted_43fa9741277b_iv -in .travis_rsa.enc -out .travis_rsa -d || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && cp .travis_rsa ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && chmod 600 ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config || :'
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = bash ];then version="--bash";fi'
  #- brew update >& /dev/null && brew upgrade >& /dev/null # takes too much time... courses fail...
  #- brew update >& /dev/null # even this make timeout, at brew-file update
  - brewprefix=$(brew --prefix)
install:
  - '[ "$coveralls" = "coveralls-python" ] && sudo pip install coveralls >/dev/null || :'
  - '[ "$coveralls" = "python-coveralls" ] && sudo pip -e . --use-mirrors >/dev/null || :'
  - brew tap homebrew/dupes # needed, as current travis environment is old and has some packages which are now under dupes, but travis environment doesn't have dupes tap.
  - cd ../
  - git clone git@github.com:rcmdnk/BrewfileTest
  - cd BrewfileTest
  - cp ../homebrew-file/BrewfileTest ./Brewfile
  - cp ../homebrew-file/BrewfileExt ./BrewfileExt
  - cp ../homebrew-file/BrewfileHome ~/.Brewfile
  - git add -A && git commit -a -m "init" && git push -f || echo nothing to be done
  - cd ../homebrew-file
  - rm -rf ../BrewfileTest
before_script:
  - exe=$(pwd)/bin/brew-file
  - git config --global push.default simple # to suppress git warning
script:
  - brew list
  - coverage run --parallel-mode $exe set_repo -r rcmdnk/BrewfileTest -y -V 2
  - cp $brewprefix/Library/rcmdnk_BrewfileTest/Brewfile .
  - rm -rf /usr/local/lib/python2.7/site-packages
  - rm -rf /usr/local/bin/easy_install
  - rm -rf /usr/local/bin/easy_install-2.7
  - rm -rf /usr/local/bin/pip
  - rm -rf /usr/local/bin/pip2
  - rm -rf /usr/local/bin/pip2.7
  - coverage run --parallel-mode $exe brew install python
  - hash -r
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always

