language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - brew install rcmdnk/homebrew-file/brew-file

# command to run tests
script: test.sh
