language: objective-c
env:
  global:
    - PAGER=cat
    - EDITOR=cat
    - VISUAL=cat
before_script:
  - brew update
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = python ];then version="--python";fi'
script:
  - brew install rcmdnk/file/brew-file $version
  - alias brew="brew-wrap"
  - brew file version
  - brew file help
  - brew install vim --with-lua --HEAD >/dev/null
  - brew install wget --enable-debug --enable-iri >/dev/null
  - brew install caskroom/cask/brew-cask >/dev/null
  - brew cask install firefox >/dev/null
  - touch "$(brew --prefix)/Library/Brewfile"
  - brew file init -y -U
  - brew file update -y -U
  - brew file casklist
  - brew file edit
  - brew file set_repo -r https://github.com/rcmdnk/BrewfileTest -y
  - brew file install -U
  - brew file update -y -U
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always
