os:
  - osx
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - brew update
# command to install dependencies
install:
  - brew install rcmdnk/homebrew-file/brew-file

# command to run tests
script: ./test.sh
