language: objective-c
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
env:
  global:
    - PAGER=cat
    - EDITOR=cat
  matrix:
    - version="--devel"
    - version="--HEAD"


# command to run tests
script: ./test.sh
