language: objective-c
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#install:
  - brew install rcmdnk/file/brew-file --python

# command to run tests
script:
  - brew file version
  - brew file help
  - brew install vim --with-lua --HEAD
  - brew install caskroom/cask/brew-file
  - brew cask install firefox
  - brew file init
  - brew file update
  - brew file casklist
  - brew file edit
