language: objective-c
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
env:
  - PAGER=cat
  - EDITOR=cat
  - version="--devel"
  - version="--HEAD"


# command to run tests
script: ./test.sh
