language: objective-c
env:
  global:
    - PAGER=cat
    - EDITOR=cat
    - VISUAL=cat
  matrix:
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
before_install:
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = python ];then version="--python";fi'
  - brew update >& /dev/null && brew upgrade >& /dev/null
install:
  - '[ "$coveralls" = "coveralls-python" ] && sudo pip install coveralls || :'
  - '[ "$coveralls" = "python-coveralls" ] && sudo pip -e . --use-mirrors || :'
  - brew install rcmdnk/file/brew-file $version
  - brew install vim --with-lua --HEAD
  - brew install caskroom/cask/brew-cask
  - brew cask install firefox
  - touch "$(brew --prefix)/Library/Brewfile"
  - exe=$(which brew-file)
script:
  - coverage run --parallel-mode $exe version
  - coverage run --parallel-mode $exe help
  - coverage run --parallel-mode $exe init -y -U
  - coverage run --parallel-mode $exe update -y -U
  - coverage run --parallel-mode $exe casklist
  - coverage run --parallel-mode $exe edit
  - coverage run --parallel-mode $exe set_repo -r https://github.com/rcmdnk/BrewfileTest -y
  - coverage run --parallel-mode $exe install -U
  - coverage run --parallel-mode $exe update -y -U
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always
