language: objective-c
branches:
  except:
    - /^v[0-9]/
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
  matrix:
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
before_install:
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && openssl aes-256-cbc -K $encrypted_43fa9741277b_key -iv $encrypted_43fa9741277b_iv -in .travis_rsa.enc -out .travis_rsa -d || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && cp .travis_rsa ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && chmod 600 ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config || :'
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = bash ];then version="--bash";fi'
  #- brew update >& /dev/null && brew upgrade >& /dev/null # takes too much time... courses fail...
  #- brew update >& /dev/null # even this make timeout, at brew-file update
  - brewprefix=$(brew --prefix)
install:
  - brew install rcmdnk/file/brew-file $version
script:
  - python --version
  - ./pyvtest.py
  - ./pyvtest2.py
  - python pyvtest.py
  - python pyvtest2.py
  - brew rm wget
  - ./bin/brew-file init -y -V 2
  - ./bin/brew-file  brew install wget --with-iri
  - brew rm wget
  - rm -rf /usr/local/lib/python2.7/site-packages
  - rm -rf /usr/local/bin/easy_install
  - rm -rf /usr/local/bin/easy_install-2.7
  - rm -rf /usr/local/bin/pip
  - rm -rf /usr/local/bin/pip2
  - rm -rf /usr/local/bin/pip2.7
  - brew file install python
  - ./bin/brew-file  brew install wget --with-iri
  - brew rm wget
  - hash -r
  - ./bin/brew-file  brew install wget --with-iri
  - brew rm wget
  - python --version
  - which python
  - python --version
  - hash -r
  - which python
  - python --version
  - /usr/bin/env python --version
  - 'coverage run --parallel-mode $exe brew install wget --with-iri || :'
  - ./pyvtest.py
  - ./pyvtest2.py
  - python pyvtest.py
  - python pyvtest2.py
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always

