language: objective-c
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
  matrix:
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_43fa9741277b_key -iv $encrypted_43fa9741277b_iv -in .travis_rsa.enc -out .travis_rsa -d
  - cp .travis_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = python ];then version="--python";fi'
  #- brew update >& /dev/null && brew upgrade >& /dev/null # takes too much time... courses fail...
install:
  - '[ "$coveralls" = "coveralls-python" ] && sudo pip install coveralls >/dev/null || :'
  - '[ "$coveralls" = "python-coveralls" ] && sudo pip -e . --use-mirrors >/dev/null || :'
  - brew install rcmdnk/file/brew-file $version
  - brew install vim --with-lua --HEAD # for option check test
  - brew install caskroom/cask/brew-cask
  - brew cask install firefox # for brew cask list test
  - brew tap homebrew/dupes # needed, as current travis environment is old and has some packages which are now under dupes, but travis environment doesn't have dupes tap.
before_script:
  - touch "$(brew --prefix)/Library/Brewfile"
  - exe=$(which brew-file)
  - git config --global push.default simple # to suppress git warning
script:
  - coverage run --parallel-mode $exe version
  - coverage run --parallel-mode $exe help
  - coverage run --parallel-mode $exe brew list >/dev/null
  - coverage run --parallel-mode $exe init -y -V 0
  - coverage run --parallel-mode $exe update -y -U -V 1
  - coverage run --parallel-mode $exe casklist -V 2
  - coverage run --parallel-mode $exe edit
  - coverage run --parallel-mode $exe set_repo -r git@github.com:rcmdnk/BrewfileTest -y -V 2
  - cp $(brew --prefix)/Library/rcmdnk_BrewfileTest/Brewfile .
  - coverage run --parallel-mode $exe install -U -V 0
  - coverage run --parallel-mode $exe update -y -U -V 0
  - export HOMEBREW_CASK_OPT="--caskroom=/opt/homebrew-cask/Caskroom"
  - coverage run --parallel-mode $exe cask_upgrade -V 0
  - coverage run --parallel-mode $exe pull -V 0
  - cp Brewfile $(brew --prefix)/Library/rcmdnk_BrewfileTest/Brewfile
  - coverage run --parallel-mode $exe push -V 0
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always
